# Generated by Django 4.2.7 on 2024-02-26 08:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Sualın nömrəsi')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exam_questions/', verbose_name='Sual')),
                ('question', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(verbose_name='Bal')),
            ],
            options={
                'verbose_name': 'İmtahan sualı',
                'verbose_name_plural': 'İmtahan sualları',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=1, verbose_name='Variant')),
                ('name', models.CharField(max_length=50, verbose_name='İmtahan növü')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='İmtahan növü slug')),
                ('exam_status', models.BooleanField(default=False, verbose_name='İmtahanın statusu')),
                ('exam_duration', models.IntegerField(verbose_name='İmtahan müddəti')),
            ],
            options={
                'verbose_name': 'İmtahan növü',
                'verbose_name_plural': 'İmtahan növləri',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='question_answers/', verbose_name='Şəkilli cavab')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Cavab')),
                ('answer_variant', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Variant')),
                ('is_correct', models.BooleanField(verbose_name='Düzgün cavab')),
            ],
            options={
                'verbose_name': 'Sualın Cavabı',
                'verbose_name_plural': 'Sualın Cavabları',
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Tələbənin seçdiyi imtahan tarixi')),
                ('exam_time', models.TimeField(blank=True, null=True, verbose_name='Tələbənin seçdiyi imtahan vaxtı')),
                ('is_finished', models.BooleanField(default=False, verbose_name='İmtahan bitib')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examtype', verbose_name='İmtahan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Tələbənin İmtahan Qeydiyyatı',
                'verbose_name_plural': 'Tələbənin İmtahan Qeydiyyatları',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_variant', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Tələbənin cavabı')),
                ('given_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestion', verbose_name='Sual')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Tələbənin Cavabı',
                'verbose_name_plural': 'Tələbənin Cavabları',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0, verbose_name='Nəticə')),
                ('right_answers', models.PositiveIntegerField(default=0, verbose_name='Düzgün cavabların sayı')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Səhv cavabların sayı')),
                ('exam_answers', models.ManyToManyField(blank=True, related_name='exam_answers', to='exam.questionanswer', verbose_name='İmtahanın Cavabları')),
                ('student_answers', models.ManyToManyField(blank=True, related_name='student_answers', to='exam.studentanswer', verbose_name='Tələbənin Cavabları')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.studentexam', verbose_name='Tələbənin İmtahanı')),
            ],
            options={
                'verbose_name': 'İmtahan nəticəsi',
                'verbose_name_plural': 'İmtahan nəticələri',
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='question_answers', to='exam.questionanswer', verbose_name='Sualın Cavabları'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=1, verbose_name='Variant')),
                ('exam_name', models.CharField(max_length=50, verbose_name='İmtahan adı')),
                ('exam_name_slug', models.SlugField(blank=True, null=True, verbose_name='İmtahan adı slug')),
                ('listening', models.FileField(blank=True, null=True, upload_to='listenings/', verbose_name='Listening')),
                ('reading', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Reading')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='exam.examtype', verbose_name='İmtahan növü')),
                ('questions', models.ManyToManyField(blank=True, related_name='exam_questions', to='exam.examquestion', verbose_name='İmtahan sualları')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahanlar',
            },
        ),
    ]
